import '@/styles/globals.css'

import { CssBaseline, ThemeProvider } from '@mui/material'
import type { AppProps } from 'next/app'
import Head from 'next/head'

import { theme } from '@/common/theme'
import Header from '@/pages/components/header'

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Тестовое задание</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <CssBaseline />

        <Header />
        <main>
          <Component {...pageProps} />
        </main>
      </ThemeProvider>
    </>
  )
}

export default App
